# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "store.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import module_pb2 as module__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bstore.proto\x12\x05proto\x1a\x0cmodule.proto"Q\n\nGetRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c"`\n\nSetRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x0c"T\n\rDeleteRequest\x12\x11\n\tplugin_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\x12\x0b\n\x03key\x18\x04 \x01(\t2\x8b\x01\n\x05Store\x12,\n\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x12&\n\x03Set\x12\x11.proto.SetRequest\x1a\x0c.proto.Empty\x12,\n\x06\x44\x65lete\x12\x14.proto.DeleteRequest\x1a\x0c.proto.EmptyB\tZ\x07./protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "store_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\007./proto"
    _globals["_GETREQUEST"]._serialized_start = 36
    _globals["_GETREQUEST"]._serialized_end = 117
    _globals["_GETRESPONSE"]._serialized_start = 119
    _globals["_GETRESPONSE"]._serialized_end = 147
    _globals["_SETREQUEST"]._serialized_start = 149
    _globals["_SETREQUEST"]._serialized_end = 245
    _globals["_DELETEREQUEST"]._serialized_start = 247
    _globals["_DELETEREQUEST"]._serialized_end = 331
    _globals["_STORE"]._serialized_start = 334
    _globals["_STORE"]._serialized_end = 473
# @@protoc_insertion_point(module_scope)
